# Generated by Django 3.0.5 on 2020-05-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Askdoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=20)),
                ('looking', models.CharField(choices=[('Just Information', 'Just Information'), ('Treatment Details', 'Treatment Details')], default='information', max_length=20)),
                ('email', models.EmailField(default='null', max_length=254)),
                ('selphone', models.CharField(choices=[('91', '+91'), ('92', '+92'), ('93', '+93'), ('94', '+94'), ('95', '+95'), ('96', '+96')], default='91', max_length=10)),
                ('contactnumber', models.CharField(default='null', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(default='null', max_length=200)),
                ('message', models.CharField(default='null', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Contactlogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(default='null', max_length=200)),
                ('message', models.CharField(default='null', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineOrdered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Combiflam', models.IntegerField(default=0)),
                ('Paracetamol', models.IntegerField(default=0)),
                ('Cofsils', models.IntegerField(default=0)),
                ('DigeneTablet', models.IntegerField(default=0)),
                ('DigeneGel', models.IntegerField(default=0)),
                ('Hajmola', models.IntegerField(default=0)),
                ('Seacod', models.IntegerField(default=0)),
                ('Shelcal', models.IntegerField(default=0)),
                ('Crocin', models.IntegerField(default=0)),
                ('Lubrifresh', models.IntegerField(default=0)),
                ('Dettol', models.IntegerField(default=0)),
                ('Ashwagandha', models.IntegerField(default=0)),
                ('Moov', models.IntegerField(default=0)),
                ('Zandu', models.IntegerField(default=0)),
                ('Vicks', models.IntegerField(default=0)),
                ('Chyawanprash', models.IntegerField(default=0)),
                ('totalSum', models.IntegerField(default=0)),
                ('storeemail', models.EmailField(default='null', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('mes_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
                ('mname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(default='null', max_length=254)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('rather', 'RatherNotSay')], default='male', max_length=10)),
                ('selphone', models.CharField(choices=[('91', '+91'), ('92', '+92'), ('93', '+93'), ('94', '+94'), ('95', '+95'), ('96', '+96')], default='91', max_length=10)),
                ('contactnumber', models.CharField(default='null', max_length=10)),
                ('password', models.CharField(default='null', max_length=20)),
                ('cpassword', models.CharField(default='null', max_length=20)),
                ('address', models.CharField(default='null', max_length=20)),
            ],
        ),
    ]
