# Generated by Django 3.0.5 on 2020-05-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineordered',
            name='storeemail',
        ),
        migrations.AlterField(
            model_name='medicineordered',
            name='totalSum',
            field=models.CharField(max_length=100),
        ),
    ]
