# Generated by Django 3.0.5 on 2020-05-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_auto_20200512_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineordered',
            name='storeemail',
            field=models.EmailField(default='null', max_length=254),
        ),
        migrations.AlterField(
            model_name='medicineordered',
            name='totalSum',
            field=models.CharField(max_length=500),
        ),
    ]
