# Generated by Django 3.0.5 on 2020-05-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_auto_20200512_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineordered',
            name='totalSum',
            field=models.IntegerField(default=0),
        ),
    ]
