# Generated by Django 3.0.5 on 2020-05-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_auto_20200512_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineordered',
            name='totalSum',
            field=models.BigIntegerField(default=0),
        ),
    ]
