# Generated by Django 3.0.5 on 2020-05-12 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicines', '0005_auto_20200512_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineordered',
            name='storeemail',
        ),
        migrations.AddField(
            model_name='medicineordered',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
