# Generated by Django 3.0.5 on 2020-05-16 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0011_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
